common:
  name: "glance"
  service:
    servicePort: 8080
    containerPort: 8080
  deployment:
    port: 8080
    args:
      - "--config"
      - "/mnt/glance.yml"
  image:
    repository: glanceapp/glance
    tag: v0.6.3
    pullPolicy: IfNotPresent
  configMap:
    enabled: true
    data:
      - name: "config"
        mountPath: "/mnt"
        data:
          - content:
              glance.yml: |
                pages:
                  - name: Home
                    columns:
                      - size: small
                        widgets:
                          - type: calendar

                          - type: rss
                            limit: 10
                            collapse-after: 3
                            cache: 3h
                            feeds:
                              - url: https://justingarrison.com/index.xml
                              - url: https://https://a-cup-of.coffee/index.xml
                                title: a cup of coffee
                              - url: https://samwho.dev/rss.xml
                              - url: https://blog.stonegarden.dev/index.xml
                              - url: https://ishadeed.com/feed.xml
                                title: Ahmad Shadeed

                          - type: twitch-channels
                            channels:
                              - cuistops
                              - cohhcarnage
                              - christitustech
                              - blurbs
                              - asmongold
                              - jembawls

                      - size: full
                        widgets:
                          - type: hacker-news

                          - type: videos
                            channels:
                              - UCR-DXc1voovS8nhAvccRZhg # Jeff Geerling
                              - UCv6J_jJa8GJqFwQNgNrMuww # ServeTheHome
                              - UCOk-gHyjcWZNj3Br4oxwh0A # Techno Tim

                          - type: reddit
                            subreddit: selfhosted

                      - size: small
                        widgets:
                          - type: weather
                            location: Lyon, France

                          - type: markets
                            markets:
                              - symbol: BTC-USD
                                name: Bitcoin
                              - symbol: NVDA
                                name: NVIDIA
                              - symbol: AAPL
                                name: Apple
                              - symbol: MSFT
                                name: Microsoft
                              - symbol: GOOGL
                                name: Google
                              - symbol: AMD
                                name: AMD
                              - symbol: RDDT
                                name: Reddit
  startupProbeEnabled: false
  startupProbe: {}
  readinessProbeEnabled: false
  readinessProbe: {}
  livenessProbeEnabled: false
  livenessProbe: {}
  persistence:
    enabled: true
    volumes: []
  ingress:
    enabled: true
    hostName: glance.your-domain.com
    ingressClassName: ""
    extraLabels: {}
    tls:
      enabled: true
      secretName: glance
    annotations:
      {}
      # cert-manager.io/cluster-issuer: cloudflare
