apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.imagePullSecret }}
spec:
  refreshInterval: {{ .Values.secretStore.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: {{ .Values.imagePullSecret }}
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: {{ .Values.vault.key }}
        property: dockerconfigjson
