---
define: &containerPort 9117

common:
  name: "jackett"
  define: &containerPort 9117

  service:
    servicePort: *containerPort
    type: ClusterIP

  deployment:
    port: *containerPort
    memoryRequest: null
    cpuRequest: null
    memoryLimit: null
    cpuLimit: null
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 25%
        maxSurge: 25%

  # container
  image:
    repositorySettings:
      isPrivate: false
      secretName: null
    repository: linuxserver/jackett
    tag: 0.22.2132
    pullPolicy: Always

  # ingress
  ingress:
    enabled: false
    hostName: toto.lan
    extraLabels: {}
    annotations:
      {}
      # nginx.ingress.kubernetes.io/proxy-body-size: 100m
    tls:
      enabled: false
      secretName: "secret-jackett-tls"
    # For Ingress CRD
    ingressClassName: istio

  # env variables
  variables:
    secret: {}
    nonSecret:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
      AUTO_UPDATE: true

  # horizontal autoscaler
  hpa:
    enabled: false
    minReplicas: 1
    maxReplicas: 2
    avgCpuUtilization: 50

  # startupProbe
  startupProbeEnabled: false
  startupProbe:
    httpGet:
      path: "/"
      port: *containerPort
    periodSeconds: 10
    failureThreshold: 20
    timeoutSeconds: 1

  # readinessProbe
  readinessProbeEnabled: true
  readinessProbe:
    tcpSocket:
      port: *containerPort
    initialDelaySeconds: 30
    periodSeconds: 30
    failureThreshold: 2
    timeoutSeconds: 3

  # livenessProbe
  livenessProbeEnabled: true
  livenessProbe:
    tcpSocket:
      port: *containerPort
    initialDelaySeconds: 30
    periodSeconds: 60
    failureThreshold: 1
    timeoutSeconds: 3

  persistence:
    enabled: true
    volumes:
      - name: "config"
        storageClassName: "" # leave empty if you want to use default
        size: "2Gi"
        pvcClaim: "" # Fill only if you want to use existing pvc
        containerMount: "/config/"
      - name: "downloads" # OPTIONAL
        storageClassName: "" # leave empty if you want to use default
        size: "1Gi"
        pvcClaim: "" # Fill only if you want to use existing pvc
        containerMount: "/downloads/"

  tests:
    classicHttp: # default helm test method
      enabled: false
    curlHostHeader: # curl using ingress.hostName as Host in header
      enabled: true
      path: "/"
