---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    - name: https
      port: {{ .Values.server.port }}
      targetPort: {{ .Values.server.port }}
