{{ if .Values.secrets.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.postgres.name }}
type: Opaque
stringData:
{{- range $key, $value := .Values.secrets.postgres.data }}
  {{ $key }}: {{ $value }}
{{- end }}
{{ end }}
---
{{ if .Values.secrets.rabbitmq.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.rabbitmq.name }}
type: Opaque
stringData:
{{- range $key, $value := .Values.secrets.rabbitmq.data }}
  {{ $key }}: {{ $value }}
{{- end }}
{{ end }}
---
{{ if .Values.secrets.kyoo.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.kyoo.name }}
type: Opaque
stringData:
{{- range $key, $value := .Values.secrets.kyoo.data }}
  {{ $key }}: {{ $value }}
{{- end }}
{{ end }}
---
{{ if .Values.secrets.meilisearch.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.meilisearch.name }}
type: Opaque
stringData:
{{- range $key, $value := .Values.secrets.meilisearch.data }}
  {{ $key }}: {{ $value }}
{{- end }}
{{ end }}
---


